export interface N3Kanji {
  kanji: string;
  meaning: string;
  onyomi: string;
  kunyomi: string;
}

// 370 kanji JLPT N3 (non-cumulative, di luar kanji N5 & N4), urutan & bacaan
// mengikuti daftar standar JLPT.
export const N3_KANJI_DATA: N3Kanji[] = [
  { kanji: '政', meaning: 'government, politics', onyomi: 'sei, sho', kunyomi: 'matsurigoto' },
  { kanji: '議', meaning: 'discuss, debate, meeting', onyomi: 'gi', kunyomi: '—' },
  { kanji: '民', meaning: 'people, nation', onyomi: 'min', kunyomi: 'tami' },
  { kanji: '連', meaning: 'join, connect', onyomi: 'ren', kunyomi: 'tsura-naru, tsu-reru' },
  { kanji: '対', meaning: 'opposite, oppose', onyomi: 'tai, tsui', kunyomi: '—' },
  { kanji: '部', meaning: 'section, department', onyomi: 'bu', kunyomi: '—' },
  { kanji: '合', meaning: 'match, fit, combine', onyomi: 'gou, ka, ga', kunyomi: 'a-waseru, a-wasu, a-u' },
  { kanji: '市', meaning: 'city, town, market', onyomi: 'shi', kunyomi: 'ichi' },
  { kanji: '内', meaning: 'inside, within', onyomi: 'nai, dai', kunyomi: 'uchi' },
  { kanji: '相', meaning: 'mutual, together', onyomi: 'sou, shou', kunyomi: 'ai' },
  { kanji: '定', meaning: 'determine, decide, fix', onyomi: 'tei, jou', kunyomi: 'sada-meru, sada-maru, sada-ka' },
  { kanji: '回', meaning: 'turn around, revolve', onyomi: 'kai, e', kunyomi: 'mawa-ru, mawa-su' },
  { kanji: '選', meaning: 'choose, select, elect', onyomi: 'sen', kunyomi: 'era-bu' },
  { kanji: '米', meaning: 'rice, USA', onyomi: 'bei, mai', kunyomi: 'kome' },
  { kanji: '実', meaning: 'reality, truth', onyomi: 'jitsu', kunyomi: 'mi, mino-ru' },
  { kanji: '関', meaning: 'relate, involve', onyomi: 'kan', kunyomi: 'seki, kaka-waru' },
  { kanji: '決', meaning: 'decide, determine', onyomi: 'ketsu', kunyomi: 'ki-meru, ki-maru' },
  { kanji: '全', meaning: 'all, whole, complete', onyomi: 'zen', kunyomi: 'matta-ku, sube-te' },
  { kanji: '表', meaning: 'surface, table, chart', onyomi: 'hyou', kunyomi: 'omote, arawa-reru, arawa-su' },
  { kanji: '戦', meaning: 'war, battle, fight', onyomi: 'sen', kunyomi: 'ikusa, tataka-u' },
  { kanji: '経', meaning: 'pass through, longitude', onyomi: 'kei, kyo', kunyomi: 'he-ru, ta-tsu' },
  { kanji: '最', meaning: 'utmost, most', onyomi: 'sai', kunyomi: 'motto-mo' },
  { kanji: '現', meaning: 'appear, actual, present', onyomi: 'gen', kunyomi: 'arawa-reru, arawa-su, utsu-tsu' },
  { kanji: '調', meaning: 'investigate, tune, harmonize', onyomi: 'chou', kunyomi: 'totono-eru, totono-u, shira-beru' },
  { kanji: '化', meaning: 'transform, change, chemistry', onyomi: 'ka, ke', kunyomi: 'ba-keru, ba-kasu, fu-keru' },
  { kanji: '当', meaning: 'hit', onyomi: 'tou', kunyomi: 'a-teru, a-taru' },
  { kanji: '約', meaning: 'promise, approximately', onyomi: 'yaku', kunyomi: 'tsuzu-maru' },
  { kanji: '首', meaning: 'neck', onyomi: 'shu', kunyomi: 'kubi' },
  { kanji: '法', meaning: 'method, law, rule', onyomi: 'hou, ho, ha', kunyomi: 'nori' },
  { kanji: '性', meaning: 'sex, gender, nature', onyomi: 'sei, shou', kunyomi: '—' },
  { kanji: '的', meaning: 'target, mark', onyomi: 'teki', kunyomi: 'mato' },
  { kanji: '要', meaning: 'main point, necessary', onyomi: 'you', kunyomi: 'i-ru, kaname' },
  { kanji: '制', meaning: 'system, control, rule', onyomi: 'sei', kunyomi: '—' },
  { kanji: '治', meaning: 'reign over, govern, cure', onyomi: 'ji, chi', kunyomi: 'osa-maru, osa-meru, nao-su, nao-ru' },
  { kanji: '務', meaning: 'task, duty', onyomi: 'mu', kunyomi: 'tsuto-meru, tsuto-maru' },
  { kanji: '成', meaning: 'turn into, achieve', onyomi: 'sei, jou', kunyomi: 'na-ru' },
  { kanji: '期', meaning: 'period, time, season', onyomi: 'ki, go', kunyomi: '—' },
  { kanji: '取', meaning: 'take, fetch', onyomi: 'shu', kunyomi: 'to-ru' },
  { kanji: '都', meaning: 'metropolis, capital', onyomi: 'to, tsu', kunyomi: 'miyako' },
  { kanji: '和', meaning: 'harmony, peace, Japanese', onyomi: 'wa, o', kunyomi: 'yawa-rageru, yawa-ragu, nago-yaka, nago-mu' },
  { kanji: '機', meaning: 'machine, opportunity', onyomi: 'ki', kunyomi: 'hata' },
  { kanji: '平', meaning: 'flat, even, calm', onyomi: 'hei, byou', kunyomi: 'tai-ra, hira' },
  { kanji: '加', meaning: 'add, append, join', onyomi: 'ka', kunyomi: 'kuwa-waru, kuwa-eru' },
  { kanji: '受', meaning: 'receive, accept', onyomi: 'ju', kunyomi: 'u-keru, u-karu' },
  { kanji: '続', meaning: 'continue, series', onyomi: 'zoku', kunyomi: 'tsuzu-keru, tsuzu-ku' },
  { kanji: '進', meaning: 'advance, proceed', onyomi: 'shin', kunyomi: 'susu-mu' },
  { kanji: '数', meaning: 'number', onyomi: 'suu, su', kunyomi: 'kazu, kazo-eru' },
  { kanji: '記', meaning: 'write down, record', onyomi: 'ki', kunyomi: 'shiru-su' },
  { kanji: '初', meaning: 'first time, beginning', onyomi: 'sho', kunyomi: 'hatsu, haji-mete, haji-me, so-meru, ui' },
  { kanji: '指', meaning: 'finger, point to, indicate', onyomi: 'shi', kunyomi: 'yubi, sa-su' },
  { kanji: '権', meaning: 'right, power, authority', onyomi: 'gon, ken', kunyomi: '—' },
  { kanji: '支', meaning: 'branch, support', onyomi: 'shi', kunyomi: 'sasa-eru' },
  { kanji: '産', meaning: 'give birth, produce', onyomi: 'san', kunyomi: 'u-mu, u-mareru, ubu' },
  { kanji: '点', meaning: 'spot, point, mark, dot', onyomi: 'ten', kunyomi: 'tsu-keru, ta-teru' },
  { kanji: '報', meaning: 'report, inform, reward', onyomi: 'hou', kunyomi: 'mukku-iru' },
  { kanji: '済', meaning: 'settle, conclude, finish', onyomi: 'sai', kunyomi: 'su-mu, su-masu' },
  { kanji: '活', meaning: 'active, lively, vigor', onyomi: 'katsu', kunyomi: '—' },
  { kanji: '原', meaning: 'field, original', onyomi: 'gen', kunyomi: 'hara' },
  { kanji: '共', meaning: 'together', onyomi: 'kyou', kunyomi: 'tomo' },
  { kanji: '得', meaning: 'gain, earn, profit', onyomi: 'toku', kunyomi: 'e-ru, u-ru' },
  { kanji: '解', meaning: 'solve, clarify, unravel', onyomi: 'kai, ge', kunyomi: 'to-keru, to-ku, to-kasu' },
  { kanji: '交', meaning: 'cross, intersect', onyomi: 'kou', kunyomi: 'maji-waru, ma-zeru, ma-jiru, maji-eru, ma-zaru, ka-wasu, ka-u' },
  { kanji: '資', meaning: 'assets, resources, capital', onyomi: 'shi', kunyomi: '—' },
  { kanji: '予', meaning: 'beforehand, in advance', onyomi: 'yo, sha', kunyomi: 'arakaji-me' },
  { kanji: '向', meaning: 'facing, turn toward', onyomi: 'kou', kunyomi: 'mu-ku, muka-i, mu-ko, mu-keru, mu-kau' },
  { kanji: '際', meaning: 'occasion, side, verge', onyomi: 'sai', kunyomi: 'kiwa' },
  { kanji: '勝', meaning: 'victory, win', onyomi: 'shou', kunyomi: 'ka-tsu, masa-ru' },
  { kanji: '面', meaning: 'face, surface, aspect', onyomi: 'men', kunyomi: 'omo, omote, tsura' },
  { kanji: '告', meaning: 'tell, announce, inform', onyomi: 'koku', kunyomi: 'tsu-geru' },
  { kanji: '反', meaning: 'oppose, anti-', onyomi: 'hon, han, tan', kunyomi: 'so-ru, so-rasu' },
  { kanji: '判', meaning: 'judge, seal', onyomi: 'han, ban', kunyomi: '—' },
  { kanji: '認', meaning: 'acknowledge, recognize', onyomi: 'nin', kunyomi: 'mito-meru, shitata-meru' },
  { kanji: '参', meaning: 'visit shrine, join, participate', onyomi: 'san', kunyomi: 'mai-ru' },
  { kanji: '利', meaning: 'profit, advantage, benefit', onyomi: 'ri', kunyomi: 'ki-ku' },
  { kanji: '組', meaning: 'construct, assemble, group', onyomi: 'so', kunyomi: 'ku-mu, kumi' },
  { kanji: '信', meaning: 'believe, trust, faith', onyomi: 'shin', kunyomi: '—' },
  { kanji: '在', meaning: 'exist', onyomi: 'zai', kunyomi: 'a-ru' },
  { kanji: '件', meaning: 'matter, case, affair', onyomi: 'ken', kunyomi: 'kudan' },
  { kanji: '側', meaning: 'side, flank, aspect', onyomi: 'soku', kunyomi: 'gawa, soba' },
  { kanji: '任', meaning: 'entrust, leave to, duty', onyomi: 'nin', kunyomi: 'maka-seru, maka-su' },
  { kanji: '引', meaning: 'pull, draw, tug', onyomi: 'in', kunyomi: 'hi-ku, hi-keru' },
  { kanji: '求', meaning: 'request, demand', onyomi: 'kyuu', kunyomi: 'moto-meru' },
  { kanji: '所', meaning: 'place, point, spot', onyomi: 'sho', kunyomi: 'tokoro' },
  { kanji: '次', meaning: 'next, order', onyomi: 'ji, shi', kunyomi: 'tsu-gu, tsugi' },
  { kanji: '昨', meaning: 'yesterday, previous, last', onyomi: 'saku', kunyomi: '—' },
  { kanji: '論', meaning: 'argument, discourse, theory', onyomi: 'ron', kunyomi: 'agetsura-u' },
  { kanji: '官', meaning: 'bureaucrat, government', onyomi: 'kan', kunyomi: '—' },
  { kanji: '増', meaning: 'increase', onyomi: 'zou', kunyomi: 'ma-su, fu-eru, fu-yasu' },
  { kanji: '係', meaning: 'person in charge, connect', onyomi: 'kei', kunyomi: 'kaka-ru, kakari' },
  { kanji: '感', meaning: 'sensation, feeling', onyomi: 'kan', kunyomi: '—' },
  { kanji: '情', meaning: 'emotion, feelings, sympathy', onyomi: 'jou, sei', kunyomi: 'nasa-ke' },
  { kanji: '投', meaning: 'throw, cast, pitch', onyomi: 'tou', kunyomi: 'na-geru' },
  { kanji: '示', meaning: 'show, indicate, display', onyomi: 'ji, shi', kunyomi: 'shime-su' },
  { kanji: '変', meaning: 'change, vary, abnormal', onyomi: 'hen', kunyomi: 'ka-waru, ka-eru' },
  { kanji: '打', meaning: 'hit, strike, knock', onyomi: 'da', kunyomi: 'u-tsu, bu-tsu' },
  { kanji: '直', meaning: 'straight, direct, honest', onyomi: 'choku, jiki', kunyomi: 'tada-chini, su-gu, nao-ru, nao-su' },
  { kanji: '両', meaning: 'both', onyomi: 'ryou', kunyomi: '—' },
  { kanji: '式', meaning: 'style, method, ceremony', onyomi: 'shiki', kunyomi: '—' },
  { kanji: '確', meaning: 'certain, definite, ascertain', onyomi: 'kaku', kunyomi: 'tashi-ka, tashi-kameru' },
  { kanji: '果', meaning: 'fruit', onyomi: 'ka', kunyomi: 'ha-tasu, ha-teru, ha-te' },
  { kanji: '容', meaning: 'contain, vessel, appearance', onyomi: 'you', kunyomi: '—' },
  { kanji: '必', meaning: 'invariably, without fail', onyomi: 'hitsu', kunyomi: 'kanarazu' },
  { kanji: '演', meaning: 'perform, act', onyomi: 'en', kunyomi: '—' },
  { kanji: '歳', meaning: 'age', onyomi: 'sai, sei', kunyomi: '—' },
  { kanji: '争', meaning: 'contend, dispute', onyomi: 'sou', kunyomi: 'arasou' },
  { kanji: '談', meaning: 'talk, conversation', onyomi: 'dan', kunyomi: '—' },
  { kanji: '能', meaning: 'ability, skill', onyomi: 'nou', kunyomi: '—' },
  { kanji: '位', meaning: 'rank, grade', onyomi: 'i', kunyomi: 'kurai, gurai' },
  { kanji: '置', meaning: 'placement, put, set', onyomi: 'chi', kunyomi: 'oku' },
  { kanji: '流', meaning: 'current, flow', onyomi: 'ryuu, ru', kunyomi: 'nagareru, nagarasu' },
  { kanji: '格', meaning: 'status, norm, rank', onyomi: 'kaku, kou', kunyomi: '—' },
  { kanji: '疑', meaning: 'doubt, distrust', onyomi: 'gi', kunyomi: 'utagau' },
  { kanji: '過', meaning: 'overdo, exceed, surpass', onyomi: 'ka', kunyomi: 'sugiru, sugosu' },
  { kanji: '局', meaning: 'bureau', onyomi: 'kyoku', kunyomi: '—' },
  { kanji: '放', meaning: 'set free, release', onyomi: 'hou', kunyomi: 'hanasu, hanareru' },
  { kanji: '常', meaning: 'usual, ordinary, normal', onyomi: 'jou', kunyomi: 'tsune, toko' },
  { kanji: '状', meaning: 'state, condition', onyomi: 'jou', kunyomi: '—' },
  { kanji: '球', meaning: 'ball, sphere', onyomi: 'kyuu', kunyomi: 'tama' },
  { kanji: '職', meaning: 'occupation, job', onyomi: 'shoku', kunyomi: '—' },
  { kanji: '与', meaning: 'give, provide', onyomi: 'yo', kunyomi: 'ataeru' },
  { kanji: '供', meaning: 'submit, offer, present', onyomi: 'kyou, ku', kunyomi: 'sonaeru, tomo' },
  { kanji: '役', meaning: 'role, part, duty', onyomi: 'yaku, eki', kunyomi: '—' },
  { kanji: '構', meaning: 'build, framework', onyomi: 'kou', kunyomi: 'kamau, kamaeru' },
  { kanji: '割', meaning: 'divide, split, break', onyomi: 'katsu', kunyomi: 'waru, wareru' },
  { kanji: '身', meaning: 'somebody, body', onyomi: 'shin', kunyomi: 'mi' },
  { kanji: '費', meaning: 'expense, cost, spend', onyomi: 'hi', kunyomi: 'tsuiyasu, tsuieru' },
  { kanji: '付', meaning: 'attach, append, add to', onyomi: 'fu', kunyomi: 'tsukeru, tsuku' },
  { kanji: '由', meaning: 'origin, cause, reason', onyomi: 'yu, yuu', kunyomi: 'yoshi' },
  { kanji: '説', meaning: 'theory, explanation', onyomi: 'setsu, zei', kunyomi: 'toku' },
  { kanji: '難', meaning: 'difficult', onyomi: 'nan', kunyomi: 'katai, muzukashii' },
  { kanji: '優', meaning: 'superior, excellent, gentle', onyomi: 'yuu, u', kunyomi: 'yasashii, sugureru' },
  { kanji: '夫', meaning: 'husband', onyomi: 'fu, fuu', kunyomi: 'otto' },
  { kanji: '収', meaning: 'take in, gather in', onyomi: 'shuu', kunyomi: 'osameru, osamaru' },
  { kanji: '断', meaning: 'decline, refuse, cut off', onyomi: 'dan', kunyomi: 'tatsu, kotowaru' },
  { kanji: '石', meaning: 'stone', onyomi: 'seki, shaku', kunyomi: 'ishi' },
  { kanji: '違', meaning: 'differ, difference', onyomi: 'i', kunyomi: 'chigau, chigaeru' },
  { kanji: '消', meaning: 'extinguish, erase, delete', onyomi: 'shou', kunyomi: 'kieru, kesu' },
  { kanji: '神', meaning: 'gods, deity', onyomi: 'shin, jin', kunyomi: 'kami, ko, kan' },
  { kanji: '番', meaning: 'number in series, turn', onyomi: 'ban', kunyomi: 'tugai' },
  { kanji: '規', meaning: 'regulation, rule', onyomi: 'ki', kunyomi: '—' },
  { kanji: '術', meaning: 'technique, skill, trick', onyomi: 'jutsu', kunyomi: '—' },
  { kanji: '備', meaning: 'provide for, prepare', onyomi: 'bi', kunyomi: 'sonaeru, sonawaru' },
  { kanji: '宅', meaning: 'home, house, residence', onyomi: 'taku', kunyomi: '—' },
  { kanji: '害', meaning: 'harm, damage, injury', onyomi: 'gai', kunyomi: '—' },
  { kanji: '配', meaning: 'distribute', onyomi: 'hai', kunyomi: 'kubaru' },
  { kanji: '警', meaning: 'admonish, warn', onyomi: 'kei', kunyomi: '—' },
  { kanji: '育', meaning: 'grow, bring up, raise', onyomi: 'iku', kunyomi: 'sodatsu, sodateru' },
  { kanji: '席', meaning: 'seat', onyomi: 'seki', kunyomi: '—' },
  { kanji: '訪', meaning: 'call on, visit', onyomi: 'hou', kunyomi: 'otozureru, tazuneru' },
  { kanji: '乗', meaning: 'ride, get on', onyomi: 'jou, shou', kunyomi: 'noru' },
  { kanji: '残', meaning: 'remainder, balance', onyomi: 'zan', kunyomi: 'nokoru, nokosu' },
  { kanji: '想', meaning: 'concept, think, idea', onyomi: 'sou, so', kunyomi: '—' },
  { kanji: '声', meaning: 'voice', onyomi: 'sei, shou', kunyomi: 'koe, kowa' },
  { kanji: '助', meaning: 'help, assist, rescue', onyomi: 'jo', kunyomi: 'tasukeru, tasukaru' },
  { kanji: '労', meaning: 'labor, toil', onyomi: 'rou', kunyomi: 'itawaru, negirau' },
  { kanji: '例', meaning: 'for example, instance', onyomi: 'rei', kunyomi: 'tatoeba, tatoeru' },
  { kanji: '然', meaning: 'sort of thing, if so', onyomi: 'zen, nen', kunyomi: '—' },
  { kanji: '限', meaning: 'limit, restrict', onyomi: 'gen', kunyomi: 'kagiru, kagiri' },
  { kanji: '追', meaning: 'chase, pursue', onyomi: 'tsui', kunyomi: 'ou' },
  { kanji: '商', meaning: 'deal in, trade, merchant', onyomi: 'shou', kunyomi: 'akinau' },
  { kanji: '葉', meaning: 'leaf, foliage', onyomi: 'you', kunyomi: 'ha' },
  { kanji: '伝', meaning: 'transmit, tell, propagate', onyomi: 'den', kunyomi: 'tsutawaru, tsutaeru' },
  { kanji: '働', meaning: 'to work', onyomi: 'dou', kunyomi: 'hataraku' },
  { kanji: '形', meaning: 'shape, form, figure', onyomi: 'kei, gyou', kunyomi: 'kata, katachi' },
  { kanji: '景', meaning: 'view, scenery', onyomi: 'kei, ke', kunyomi: '—' },
  { kanji: '落', meaning: 'fall, drop', onyomi: 'raku', kunyomi: 'otosu, ochiru' },
  { kanji: '好', meaning: 'be fond, like, favorable', onyomi: 'kou', kunyomi: 'konomu, suku' },
  { kanji: '退', meaning: 'retreat, withdraw', onyomi: 'tai', kunyomi: 'shirizoku, hirabku' },
  { kanji: '頭', meaning: 'head', onyomi: 'tou, zu', kunyomi: 'atama, kashira' },
  { kanji: '負', meaning: 'lose, defeat', onyomi: 'fu', kunyomi: 'makeru, makasu' },
  { kanji: '渡', meaning: 'go across, cross over', onyomi: 'to', kunyomi: 'wataru, watasu' },
  { kanji: '失', meaning: 'lose, loss', onyomi: 'shitsu', kunyomi: 'ushinau, useru' },
  { kanji: '差', meaning: 'distinction, difference', onyomi: 'sa', kunyomi: 'sasu' },
  { kanji: '末', meaning: 'end, last part, tip', onyomi: 'matsu, batsu', kunyomi: 'sue' },
  { kanji: '守', meaning: 'guard, protect', onyomi: 'shu, su', kunyomi: 'mamoru, mori' },
  { kanji: '若', meaning: 'young', onyomi: 'jaku, nyaku', kunyomi: 'wakai, moshikuha' },
  { kanji: '種', meaning: 'kind, type, seed', onyomi: 'shu', kunyomi: 'tane, -gusa' },
  { kanji: '美', meaning: 'beauty, beautiful', onyomi: 'bi, mi', kunyomi: 'utsukushii' },
  { kanji: '命', meaning: 'fate, life force, destiny', onyomi: 'mei, myou', kunyomi: 'inochi' },
  { kanji: '福', meaning: 'blessing, fortune, happiness', onyomi: 'fuku', kunyomi: '—' },
  { kanji: '望', meaning: 'hope, wish', onyomi: 'bou, mou', kunyomi: 'nozomu' },
  { kanji: '非', meaning: 'is not, not, un-', onyomi: 'hi', kunyomi: '—' },
  { kanji: '観', meaning: 'outlook, view', onyomi: 'kan', kunyomi: '—' },
  { kanji: '察', meaning: 'inspect, investigate, guess', onyomi: 'satsu', kunyomi: '—' },
  { kanji: '段', meaning: 'grade, steps, stairs', onyomi: 'dan', kunyomi: '—' },
  { kanji: '横', meaning: 'sideways, horizontal, side', onyomi: 'ou', kunyomi: 'yoko' },
  { kanji: '深', meaning: 'deep', onyomi: 'shin', kunyomi: 'fukameru, fukamai' },
  { kanji: '申', meaning: 'to speak, ninth zodiac sign', onyomi: 'shin', kunyomi: 'mosu, moshi, saru' },
  { kanji: '様', meaning: 'Mr./Mrs., form, pattern', onyomi: 'you', kunyomi: 'sama' },
  { kanji: '財', meaning: 'property, wealth, assets', onyomi: 'zai, sai', kunyomi: '—' },
  { kanji: '港', meaning: 'port, harbor', onyomi: 'kou', kunyomi: 'minato' },
  { kanji: '識', meaning: 'discern, know', onyomi: 'shiki', kunyomi: '—' },
  { kanji: '呼', meaning: 'call, call out to, invite', onyomi: 'ko', kunyomi: 'yobu' },
  { kanji: '達', meaning: 'reach, arrive, attain', onyomi: 'tatsu, da', kunyomi: 'tachi, tooru' },
  { kanji: '良', meaning: 'good, fine', onyomi: 'ryou', kunyomi: 'yoi, ii' },
  { kanji: '阪', meaning: 'slope', onyomi: 'han', kunyomi: 'saka' },
  { kanji: '候', meaning: 'condition, state', onyomi: 'kou', kunyomi: 'sourou' },
  { kanji: '程', meaning: 'extent, degree', onyomi: 'tei', kunyomi: 'hodo' },
  { kanji: '満', meaning: 'full, satisfy', onyomi: 'man', kunyomi: 'michiru, mitasu' },
  { kanji: '敗', meaning: 'defeat, lose', onyomi: 'hai', kunyomi: 'yabureru' },
  { kanji: '値', meaning: 'price, cost', onyomi: 'chi', kunyomi: 'ne, atai' },
  { kanji: '突', meaning: 'thrust, protruding', onyomi: 'totsu, ka', kunyomi: 'tsu-ku' },
  { kanji: '光', meaning: 'ray, light', onyomi: 'kou', kunyomi: 'hikari, hika-ru' },
  { kanji: '路', meaning: 'path, route, road', onyomi: 'ro', kunyomi: 'ji' },
  { kanji: '科', meaning: 'department, course', onyomi: 'ka', kunyomi: '—' },
  { kanji: '積', meaning: 'load, pile up, stack', onyomi: 'seki', kunyomi: 'tsu-mu, tsu-moru' },
  { kanji: '他', meaning: 'other, another', onyomi: 'ta', kunyomi: 'hoka' },
  { kanji: '処', meaning: 'dispose, deal with', onyomi: 'sho', kunyomi: '—' },
  { kanji: '太', meaning: 'fat, thick', onyomi: 'tai, ta', kunyomi: 'futo-i, futo-ru' },
  { kanji: '客', meaning: 'customer, visitor, guest', onyomi: 'kyaku, kaku', kunyomi: '—' },
  { kanji: '否', meaning: 'negate, no, decline', onyomi: 'hi', kunyomi: 'ina, iya' },
  { kanji: '師', meaning: 'master, teacher', onyomi: 'shi', kunyomi: '—' },
  { kanji: '登', meaning: 'ascend, climb', onyomi: 'tou, to', kunyomi: 'nobo-ru' },
  { kanji: '易', meaning: 'easy, simple', onyomi: 'eki, i', kunyomi: 'yasa-shii' },
  { kanji: '速', meaning: 'fast, quick, speedy', onyomi: 'soku', kunyomi: 'haya-i, haya-meru, sumi-yaka' },
  { kanji: '存', meaning: 'exist', onyomi: 'son, zon', kunyomi: '—' },
  { kanji: '飛', meaning: 'fly, jump', onyomi: 'hi', kunyomi: 'to-bu, to-basu' },
  { kanji: '殺', meaning: 'kill, murder', onyomi: 'sasetsu, satsu, sai', kunyomi: 'koro-su' },
  { kanji: '号', meaning: 'number, item', onyomi: 'gou', kunyomi: '—' },
  { kanji: '単', meaning: 'simple, single', onyomi: 'tan', kunyomi: 'hitoe' },
  { kanji: '座', meaning: 'seat, sit', onyomi: 'za', kunyomi: 'suwa-ru' },
  { kanji: '破', meaning: 'rip, tear, break, destroy', onyomi: 'ha', kunyomi: 'yabu-ru, yabu-reru' },
  { kanji: '除', meaning: 'exclude, remove', onyomi: 'jo, ji', kunyomi: 'nozo-ku' },
  { kanji: '完', meaning: 'complete, perfect, finish', onyomi: 'kan', kunyomi: '—' },
  { kanji: '降', meaning: 'descend, fall, surrender', onyomi: 'kou, go', kunyomi: 'fu-ru, o-rosu, o-riru' },
  { kanji: '責', meaning: 'liability, blame, condemn', onyomi: 'seki', kunyomi: 'se-meru' },
  { kanji: '捕', meaning: 'catch, capture, arrest', onyomi: 'ho', kunyomi: 'to-ru, tsuka-maru, tsuka-maeru' },
  { kanji: '危', meaning: 'dangerous, risky, perilous', onyomi: 'ki', kunyomi: 'abu-nai, aya-bumu, aya-ui' },
  { kanji: '給', meaning: 'supply, wage, salary, provide', onyomi: 'kyuu', kunyomi: 'tama-u, tamo-u' },
  { kanji: '苦', meaning: 'suffering, hardship, bitter', onyomi: 'ku', kunyomi: 'niga-ru, niga-i, kuru-shii' },
  { kanji: '迎', meaning: 'welcome', onyomi: 'gei', kunyomi: 'muka-eru' },
  { kanji: '園', meaning: 'public park, garden', onyomi: 'en', kunyomi: 'sono' },
  { kanji: '具', meaning: 'tool, ingredients, implement', onyomi: 'gu', kunyomi: '—' },
  { kanji: '辞', meaning: 'resign, quit', onyomi: 'ji', kunyomi: 'ya-meru' },
  { kanji: '因', meaning: 'cause, factor, depends on', onyomi: 'in', kunyomi: 'yo-ru, china-mu' },
  { kanji: '馬', meaning: 'horse', onyomi: 'ba', kunyomi: 'uma, ma' },
  { kanji: '愛', meaning: 'love, affection', onyomi: 'ai', kunyomi: 'ito-shii, mana, kanashii, me-deru' },
  { kanji: '富', meaning: 'wealth, enrich, get rich', onyomi: 'fu, fuu', kunyomi: 'to-mu, tomi' },
  { kanji: '彼', meaning: 'he, him, her', onyomi: 'hi', kunyomi: 'kare, kano' },
  { kanji: '未', meaning: 'not yet, still, eighth zodiac sign', onyomi: 'mi, bi', kunyomi: 'mada, ima-da' },
  { kanji: '舞', meaning: 'dance, circle', onyomi: 'bu', kunyomi: 'ma-u, mai' },
  { kanji: '亡', meaning: 'deceased, dying', onyomi: 'bou, mou', kunyomi: 'na-kunaru' },
  { kanji: '冷', meaning: 'cool, cold, chill', onyomi: 'rei', kunyomi: 'tsume-tai, hi-eru, hi-yasu, sa-meru' },
  { kanji: '適', meaning: 'suitable, appropriate', onyomi: 'teki', kunyomi: '—' },
  { kanji: '婦', meaning: 'lady, woman, wife', onyomi: 'fu', kunyomi: 'yome' },
  { kanji: '寄', meaning: 'approach, draw near, donate', onyomi: 'ki', kunyomi: 'yo-ru, yo-seru' },
  { kanji: '込', meaning: 'crowded, mixture', onyomi: '—', kunyomi: 'ko-meru, ko-mu' },
  { kanji: '顔', meaning: 'face', onyomi: 'gan', kunyomi: 'kao' },
  { kanji: '類', meaning: 'sort, kind, type, class', onyomi: 'rui', kunyomi: 'tagu-i' },
  { kanji: '余', meaning: 'surplus, excess, remaining', onyomi: 'yo', kunyomi: 'ama-ru, ama-su' },
  { kanji: '王', meaning: 'king', onyomi: 'ou', kunyomi: '—' },
  { kanji: '返', meaning: 'return, answer', onyomi: 'hen', kunyomi: 'kae-ru, kae-su' },
  { kanji: '妻', meaning: 'wife, spouse', onyomi: 'sai', kunyomi: 'tsuma' },
  { kanji: '背', meaning: 'stature, height, back', onyomi: 'hai', kunyomi: 'somu-keru, somu-ku, sei, se' },
  { kanji: '熱', meaning: 'heat, hot, fever', onyomi: 'netsu', kunyomi: 'atsu-i' },
  { kanji: '宿', meaning: 'inn, lodging', onyomi: 'shuku', kunyomi: 'yado-ru, yado-su, yado' },
  { kanji: '薬', meaning: 'medicine, drug', onyomi: 'yaku', kunyomi: 'kusuri' },
  { kanji: '険', meaning: 'precipitous, steep, inaccessible', onyomi: 'ken', kunyomi: 'kewa-shii' },
  { kanji: '頼', meaning: 'ask for, rely on, depend on', onyomi: 'rai', kunyomi: 'tano-mu, tano-moshii, tayo-ri, tayo-ru' },
  { kanji: '覚', meaning: 'memorize, remember, wake up', onyomi: 'kaku', kunyomi: 'obo-eru, sa-meru, sa-masu' },
  { kanji: '船', meaning: 'ship, boat', onyomi: 'sen', kunyomi: 'fune, funa' },
  { kanji: '途', meaning: 'route, way, road', onyomi: 'to', kunyomi: 'michi' },
  { kanji: '許', meaning: 'permit, approve, allow, forgive', onyomi: 'kyo', kunyomi: 'yuru-su' },
  { kanji: '抜', meaning: 'pull out, extract, remove', onyomi: 'batsu', kunyomi: 'nu-keru, nu-ku, nu-karu, nu-kasu' },
  { kanji: '便', meaning: 'convenient, facility', onyomi: 'ben, bin', kunyomi: 'tayo-ri' },
  { kanji: '留', meaning: 'detain, fasten, halt, stop', onyomi: 'ryuu, ru', kunyomi: 'to-meru, to-maru, todo-meru' },
  { kanji: '罪', meaning: 'guilt, sin, crime, offense', onyomi: 'zai', kunyomi: 'tsumi' },
  { kanji: '努', meaning: 'make efforts, endeavor, exert', onyomi: 'do', kunyomi: 'tsuto-meru' },
  { kanji: '精', meaning: 'refined, spirit, life force', onyomi: 'sei, shou', kunyomi: 'shira-geru' },
  { kanji: '散', meaning: 'scatter, disperse', onyomi: 'san', kunyomi: 'chi-ru, chi-rasu, chi-rakaru, chi-rakasu' },
  { kanji: '静', meaning: 'quiet, calm', onyomi: 'sei, jou', kunyomi: 'shizu, shizu-ka, shizu-meru, shizu-maru' },
  { kanji: '婚', meaning: 'marriage', onyomi: 'kon', kunyomi: '—' },
  { kanji: '喜', meaning: 'rejoice, take pleasure in', onyomi: 'ki', kunyomi: 'yoroko-bu' },
  { kanji: '浮', meaning: 'float, rise to surface', onyomi: 'fu', kunyomi: 'u-ku, u-kareru, u-kaberu, u-kabu' },
  { kanji: '絶', meaning: 'cut off, break off, discontinue', onyomi: 'zetsu', kunyomi: 'ta-yasu, ta-tsu, ta-eru' },
  { kanji: '幸', meaning: 'happiness, blessing, fortune', onyomi: 'kou', kunyomi: 'shiawa-se, sachi, saiwa-i' },
  { kanji: '押', meaning: 'push, press', onyomi: 'ou', kunyomi: 'o-su, o-saeru' },
  { kanji: '倒', meaning: 'overthrow, fall over, collapse', onyomi: 'tou', kunyomi: 'tao-reru, tao-su' },
  { kanji: '等', meaning: 'equality, impartiality, etc.', onyomi: 'tou', kunyomi: 'hito-shii, nado' },
  { kanji: '老', meaning: 'grow old, old person', onyomi: 'rou', kunyomi: 'o-iru, fu-keru' },
  { kanji: '曲', meaning: 'bend, curve, music, song', onyomi: 'kyoku', kunyomi: 'ma-geru, ma-garu' },
  { kanji: '払', meaning: 'pay, clear away', onyomi: 'futsu', kunyomi: 'hara-u' },
  { kanji: '庭', meaning: 'courtyard, garden, yard', onyomi: 'tei', kunyomi: 'niwa' },
  { kanji: '徒', meaning: 'follower, on foot, junior, vanity', onyomi: 'to', kunyomi: '—' },
  { kanji: '勤', meaning: 'work for, serve', onyomi: 'kin, gon', kunyomi: 'tsuto-meru, tsuto-maru' },
  { kanji: '遅', meaning: 'slow, late', onyomi: 'chi', kunyomi: 'oso-i, oku-reru, oku-rasu' },
  { kanji: '居', meaning: 'reside, live, exist', onyomi: 'kyo, ko', kunyomi: 'i-ru' },
  { kanji: '雑', meaning: 'miscellaneous', onyomi: 'zatsu, zoun', kunyomi: 'maji-ru' },
  { kanji: '招', meaning: 'invite, beckon, summon', onyomi: 'shou', kunyomi: 'mane-ku' },
  { kanji: '困', meaning: 'have difficulty, become distressed', onyomi: 'kon', kunyomi: 'koma-ru' },
  { kanji: '欠', meaning: 'lack, deficiency', onyomi: 'ketsu', kunyomi: 'ka-keru, ka-ku' },
  { kanji: '更', meaning: 'renew, replace, furthermore', onyomi: 'kou', kunyomi: 'fu-keru, fu-kasu, sara' },
  { kanji: '刻', meaning: 'engrave, cut fine, chop', onyomi: 'koku', kunyomi: 'kiza-mu' },
  { kanji: '賛', meaning: 'approve of, praise, agree with', onyomi: 'san', kunyomi: '—' },
  { kanji: '抱', meaning: 'embrace, hug', onyomi: 'hou', kunyomi: 'da-ku, kaka-eru, ida-ku' },
  { kanji: '犯', meaning: 'crime, commit crime, offense', onyomi: 'han', kunyomi: 'oka-su' },
  { kanji: '恐', meaning: 'fear, dread', onyomi: 'kyou', kunyomi: 'oso-roshii, oso-reru' },
  { kanji: '息', meaning: 'breath, interest on money', onyomi: 'musu, soku', kunyomi: 'iki' },
  { kanji: '遠', meaning: 'distant, far', onyomi: 'on, en', kunyomi: 'too-i' },
  { kanji: '戻', meaning: 'return, go back', onyomi: 'rei', kunyomi: 'modo-ru, modo-su' },
  { kanji: '願', meaning: 'request, petition, wish', onyomi: 'gan', kunyomi: 'nega-u' },
  { kanji: '絵', meaning: 'picture, drawing, painting', onyomi: 'kai, e', kunyomi: 'ega-ku' },
  { kanji: '越', meaning: 'surpass, cross over', onyomi: 'etsu', kunyomi: 'ko-su, ko-eru' },
  { kanji: '欲', meaning: 'desire, greed, craving', onyomi: 'yoku', kunyomi: 'ho-shii, hos-suru' },
  { kanji: '痛', meaning: 'pain, ache, hurt', onyomi: 'tsuu', kunyomi: 'ita-i, ita-meru, ita-mu' },
  { kanji: '笑', meaning: 'laugh, smile', onyomi: 'shou', kunyomi: 'wara-u, e-mu' },
  { kanji: '互', meaning: 'mutually, reciprocally', onyomi: 'go', kunyomi: 'taga-i, katami-ni' },
  { kanji: '束', meaning: 'bundle, bunch', onyomi: 'soku', kunyomi: 'taba, tsuka' },
  { kanji: '似', meaning: 'resemble, similar', onyomi: 'ji, ne', kunyomi: 'ni-ru' },
  { kanji: '列', meaning: 'file, row, column', onyomi: 'retsu, re', kunyomi: '—' },
  { kanji: '探', meaning: 'search, look for', onyomi: 'tan', kunyomi: 'sagu-ru, saga-su' },
  { kanji: '逃', meaning: 'escape, flee', onyomi: 'tou', kunyomi: 'noga-reru, noga-su, ni-geru, ni-gasu' },
  { kanji: '遊', meaning: 'play, hang out', onyomi: 'yu', kunyomi: 'aso-bu' },
  { kanji: '迷', meaning: 'perplexed, lost', onyomi: 'mei', kunyomi: 'mayo-u' },
  { kanji: '夢', meaning: 'dream', onyomi: 'mu', kunyomi: 'yume' },
  { kanji: '君', meaning: 'you, male name suffix', onyomi: 'kun', kunyomi: 'kimi' },
  { kanji: '閉', meaning: 'closed, shut', onyomi: 'hei', kunyomi: 'shi-meru, shi-maru, to-jiru, to-zasu' },
  { kanji: '緒', meaning: 'beginning, cord, strap', onyomi: 'sho, cho', kunyomi: 'o' },
  { kanji: '折', meaning: 'fold, bend, break', onyomi: 'setsu, shaku', kunyomi: 'o-reru, o-ru, ori' },
  { kanji: '草', meaning: 'grass, weeds', onyomi: 'sou', kunyomi: 'kusa' },
  { kanji: '暮', meaning: 'dusk, livelihood', onyomi: 'bo', kunyomi: 'ku-reru, ku-rasu' },
  { kanji: '酒', meaning: 'sake, alcohol', onyomi: 'shu', kunyomi: 'sake, saka-' },
  { kanji: '悲', meaning: 'grieve, sad', onyomi: 'hi', kunyomi: 'kana-shimu, kana-shii' },
  { kanji: '晴', meaning: 'clear up, fine weather', onyomi: 'sei', kunyomi: 'ha-reru, ha-rasu' },
  { kanji: '掛', meaning: 'hang, suspend, multiply', onyomi: 'kei', kunyomi: 'ka-keru, ka-karu, kakari' },
  { kanji: '到', meaning: 'arrive, reach', onyomi: 'tou', kunyomi: 'ita-ru' },
  { kanji: '寝', meaning: 'lie down, sleep', onyomi: 'shin', kunyomi: 'ne-ru, ne-kasu' },
  { kanji: '暗', meaning: 'darkness, dark', onyomi: 'an', kunyomi: 'kura-i' },
  { kanji: '盗', meaning: 'steal, rob', onyomi: 'tou', kunyomi: 'nusu-mu' },
  { kanji: '吸', meaning: 'suck, inhale, absorb', onyomi: 'kyuu', kunyomi: 'su-u' },
  { kanji: '陽', meaning: 'sunshine, positive', onyomi: 'you', kunyomi: 'hi' },
  { kanji: '御', meaning: 'honorable, honorific', onyomi: 'gyo, go', kunyomi: 'on, o' },
  { kanji: '歯', meaning: 'tooth, cog', onyomi: 'shi', kunyomi: 'ha' },
  { kanji: '忘', meaning: 'forget', onyomi: 'bou', kunyomi: 'wasu-reru' },
  { kanji: '雪', meaning: 'snow', onyomi: 'setsu', kunyomi: 'yuki' },
  { kanji: '吹', meaning: 'blow out, puff', onyomi: 'sui', kunyomi: 'fu-ku' },
  { kanji: '娘', meaning: 'daughter, girl', onyomi: 'jou', kunyomi: 'musume, ko' },
  { kanji: '誤', meaning: 'mistake, err', onyomi: 'go', kunyomi: 'ayama-ru' },
  { kanji: '洗', meaning: 'wash', onyomi: 'sen', kunyomi: 'ara-u' },
  { kanji: '慣', meaning: 'accustomed, get used to', onyomi: 'kan', kunyomi: 'na-reru, na-rasu' },
  { kanji: '礼', meaning: 'etiquette, gratitude', onyomi: 'rei, rai', kunyomi: '—' },
  { kanji: '窓', meaning: 'window, pane', onyomi: 'sou', kunyomi: 'mado' },
  { kanji: '昔', meaning: 'long ago, old times', onyomi: 'seki, shaku', kunyomi: 'mukashi' },
  { kanji: '貧', meaning: 'poverty, poor', onyomi: 'hin, bin', kunyomi: 'mazu-shii' },
  { kanji: '怒', meaning: 'angry, offended', onyomi: 'do', kunyomi: 'oko-ru, ika-ru' },
  { kanji: '泳', meaning: 'swim', onyomi: 'ei', kunyomi: 'oyo-gu' },
  { kanji: '祖', meaning: 'ancestor, forefathers', onyomi: 'so', kunyomi: '—' },
  { kanji: '杯', meaning: 'sake cup, glass', onyomi: 'hai', kunyomi: 'sakazuki' },
  { kanji: '疲', meaning: 'tiring, fatigue', onyomi: 'hi', kunyomi: 'tsuka-reru' },
  { kanji: '皆', meaning: 'all, everybody', onyomi: 'kai', kunyomi: 'mina, minna' },
  { kanji: '鳴', meaning: 'chirp, cry, bark', onyomi: 'mei', kunyomi: 'na-ru, na-rasu, na-ku' },
  { kanji: '腹', meaning: 'abdomen, belly, stomach', onyomi: 'fuku', kunyomi: 'hara' },
  { kanji: '煙', meaning: 'smoke', onyomi: 'en', kunyomi: 'kemu-ru, kemuri, kemu-i' },
  { kanji: '眠', meaning: 'sleep', onyomi: 'min', kunyomi: 'nemu-ru, nemu-i' },
  { kanji: '怖', meaning: 'scary, afraid, fearful', onyomi: 'fu', kunyomi: 'kowa-i, o-jiru' },
  { kanji: '耳', meaning: 'ear', onyomi: 'ji', kunyomi: 'mimi' },
  { kanji: '頂', meaning: 'top, summit, peak', onyomi: 'chou', kunyomi: 'itada-ku, itadaki' },
  { kanji: '箱', meaning: 'box, case', onyomi: 'sou', kunyomi: 'hako' },
  { kanji: '晩', meaning: 'night, evening', onyomi: 'ban', kunyomi: '—' },
  { kanji: '寒', meaning: 'cold', onyomi: 'kan', kunyomi: 'samu-i' },
  { kanji: '髪', meaning: 'hair', onyomi: 'hatsu', kunyomi: 'kami' },
  { kanji: '忙', meaning: 'busy', onyomi: 'bou, mou', kunyomi: 'isoga-shii' },
  { kanji: '才', meaning: 'genius, years old', onyomi: 'sai', kunyomi: '—' },
  { kanji: '靴', meaning: 'shoes', onyomi: 'ka', kunyomi: 'kutsu' },
  { kanji: '恥', meaning: 'disgrace, shame', onyomi: 'chi', kunyomi: 'ha-zukashii, ha-jiru, ha-jirau, haji' },
  { kanji: '偶', meaning: 'by chance, even number', onyomi: 'guu', kunyomi: 'tama' },
  { kanji: '偉', meaning: 'admirable, great', onyomi: 'i', kunyomi: 'era-i' },
  { kanji: '猫', meaning: 'cat', onyomi: 'byou', kunyomi: 'neko' },
  { kanji: '幾', meaning: 'how many, how much', onyomi: 'ki', kunyomi: 'iku-tsu' },
  { kanji: '誰', meaning: 'who', onyomi: 'sui', kunyomi: 'dare' }
];
