export interface N4Kanji {
  kanji: string;
  meaning: string;
  onyomi: string;
  kunyomi: string;
}

// 167 kanji JLPT N4 (non-cumulative, di luar 80 kanji N5), urutan & bacaan
// mengikuti daftar standar JLPT.
export const N4_KANJI_DATA: N4Kanji[] = [
  { kanji: '会', meaning: 'meet, see, meeting', onyomi: 'kai', kunyomi: 'a-u' },
  { kanji: '同', meaning: 'same, equal, identical', onyomi: 'dou', kunyomi: 'ona-ji' },
  { kanji: '事', meaning: 'thing, matter', onyomi: 'ji, zu', kunyomi: 'koto' },
  { kanji: '自', meaning: 'self, oneself', onyomi: 'ji, shi', kunyomi: 'mizuka-ra' },
  { kanji: '社', meaning: 'company, shrine', onyomi: 'sha', kunyomi: 'yashiro' },
  { kanji: '発', meaning: 'departure, emit', onyomi: 'hatsu, hotsu', kunyomi: '—' },
  { kanji: '者', meaning: 'person', onyomi: 'sha', kunyomi: 'mono' },
  { kanji: '地', meaning: 'ground, earth', onyomi: 'chi, ji', kunyomi: '—' },
  { kanji: '業', meaning: 'skill, karma', onyomi: 'gyou', kunyomi: 'waza' },
  { kanji: '方', meaning: 'direction', onyomi: 'hou', kunyomi: 'kata' },
  { kanji: '新', meaning: 'new', onyomi: 'shin', kunyomi: 'atara-shii, ara-ta, nii' },
  { kanji: '場', meaning: 'location, place', onyomi: 'jou', kunyomi: 'ba' },
  { kanji: '員', meaning: 'member, personnel', onyomi: 'in', kunyomi: '—' },
  { kanji: '立', meaning: 'to stand, stand up', onyomi: 'ritsu, ryu', kunyomi: 'ta-tsu, ta-teru' },
  { kanji: '開', meaning: 'open, unfold, unseal', onyomi: 'kai', kunyomi: 'a-ku, a-keru, hira-ku, hira-keru' },
  { kanji: '手', meaning: 'hand', onyomi: 'shu', kunyomi: 'te' },
  { kanji: '力', meaning: 'power, strength', onyomi: 'riki, ryoku', kunyomi: 'chikara' },
  { kanji: '問', meaning: 'question, ask', onyomi: 'mon', kunyomi: 'to-i, to-u, ton' },
  { kanji: '代', meaning: 'substitute, replace, generation', onyomi: 'dai', kunyomi: 'ka-eru, ka-waru, shiro, yo' },
  { kanji: '明', meaning: 'bright, light, clear', onyomi: 'mei, myou', kunyomi: 'a-kasu, aka-rui, aki-raka' },
  { kanji: '動', meaning: 'move, motion, operate', onyomi: 'dou', kunyomi: 'ugo-kasu, ugo-ku' },
  { kanji: '京', meaning: 'capital city', onyomi: 'kyou, kei, kin', kunyomi: 'miyako' },
  { kanji: '目', meaning: 'eye', onyomi: 'moku, boku', kunyomi: 'me, ma' },
  { kanji: '通', meaning: 'pass through, passage', onyomi: 'tsu, tsuu', kunyomi: 'too-ru, kayo-u' },
  { kanji: '言', meaning: 'say, speak, word', onyomi: 'gen, gon', kunyomi: 'i-u, koto' },
  { kanji: '理', meaning: 'logic, reason', onyomi: 'ri', kunyomi: '—' },
  { kanji: '体', meaning: 'body, object, form', onyomi: 'tai, tei', kunyomi: 'karada' },
  { kanji: '田', meaning: 'rice field, paddy', onyomi: 'den', kunyomi: 'ta' },
  { kanji: '主', meaning: 'lord, master, main', onyomi: 'shu, su', kunyomi: 'nushi, omo' },
  { kanji: '題', meaning: 'topic, subject, title, theme', onyomi: 'dai', kunyomi: '—' },
  { kanji: '意', meaning: 'mind, meaning, intention', onyomi: 'i', kunyomi: '—' },
  { kanji: '不', meaning: 'negative, non-', onyomi: 'fu, bu', kunyomi: '—' },
  { kanji: '作', meaning: 'make, create, produce', onyomi: 'saku, sa', kunyomi: 'tsuku-ru' },
  { kanji: '用', meaning: 'utilize, use', onyomi: 'you', kunyomi: 'mochi-iru' },
  { kanji: '度', meaning: 'degrees, occasion, time', onyomi: 'do, taku', kunyomi: 'tabi, ta-i' },
  { kanji: '強', meaning: 'strong, powerful', onyomi: 'kyou, gou', kunyomi: 'tsuyo-i, shi-iru' },
  { kanji: '公', meaning: 'public, official, formal', onyomi: 'kou', kunyomi: 'oyake' },
  { kanji: '持', meaning: 'hold, have', onyomi: 'ji', kunyomi: 'mo-tsu' },
  { kanji: '野', meaning: 'field, plains', onyomi: 'ya', kunyomi: 'no' },
  { kanji: '以', meaning: 'than this, compared with', onyomi: 'i', kunyomi: '—' },
  { kanji: '思', meaning: 'think', onyomi: 'shi', kunyomi: 'omo-u' },
  { kanji: '家', meaning: 'house, home', onyomi: 'ka, ke', kunyomi: 'ie, ya, uchi' },
  { kanji: '世', meaning: 'world, society, generation', onyomi: 'sei, se', kunyomi: 'yo' },
  { kanji: '多', meaning: 'many, much', onyomi: 'ta', kunyomi: 'oo-i' },
  { kanji: '正', meaning: 'correct, true, righteous', onyomi: 'sei, shou', kunyomi: 'tada-shii, masa-ni' },
  { kanji: '安', meaning: 'cheap, safe, relieve', onyomi: 'an', kunyomi: 'yasu-i' },
  { kanji: '院', meaning: 'institution, temple', onyomi: 'in', kunyomi: '—' },
  { kanji: '心', meaning: 'heart, mind, spirit', onyomi: 'shin', kunyomi: 'kokoro' },
  { kanji: '界', meaning: 'boundary, border', onyomi: 'kai', kunyomi: '—' },
  { kanji: '教', meaning: 'teach, instruct, faith', onyomi: 'kyou', kunyomi: 'oshi-eru, oso-waru' },
  { kanji: '文', meaning: 'sentence, literature', onyomi: 'bun, mon', kunyomi: 'fumi' },
  { kanji: '元', meaning: 'origin, beginning', onyomi: 'gen, gan', kunyomi: 'moto' },
  { kanji: '重', meaning: 'heavy, duplicate', onyomi: 'juu, chou', kunyomi: 'omo-i, e, kasa-neru' },
  { kanji: '近', meaning: 'near, close', onyomi: 'kin', kunyomi: 'chika-i' },
  { kanji: '考', meaning: 'consider, think over', onyomi: 'kou', kunyomi: 'kanga-eru' },
  { kanji: '画', meaning: 'picture, painting, brush-stroke', onyomi: 'ga, kaku', kunyomi: '—' },
  { kanji: '海', meaning: 'sea, ocean', onyomi: 'kai', kunyomi: 'umi' },
  { kanji: '売', meaning: 'sell', onyomi: 'bai', kunyomi: 'u-ru' },
  { kanji: '知', meaning: 'know, wisdom', onyomi: 'chi', kunyomi: 'shi-ru' },
  { kanji: '道', meaning: 'road, way, street', onyomi: 'dou, to', kunyomi: 'michi' },
  { kanji: '集', meaning: 'gather, collect', onyomi: 'shuu', kunyomi: 'atsu-maru, atsu-meru, tsudo-u' },
  { kanji: '別', meaning: 'separate, different, another', onyomi: 'betsu', kunyomi: 'waka-reru, wa-keru' },
  { kanji: '物', meaning: 'thing, object, matter', onyomi: 'butsu, motsu', kunyomi: 'mono' },
  { kanji: '使', meaning: 'use, spend, messenger', onyomi: 'shi', kunyomi: 'tsuka-u' },
  { kanji: '品', meaning: 'goods, article', onyomi: 'hin', kunyomi: 'shina' },
  { kanji: '計', meaning: 'plot, plan, count, measure', onyomi: 'kei', kunyomi: 'haka-ru' },
  { kanji: '死', meaning: 'death, die', onyomi: 'shi', kunyomi: 'shi-nu' },
  { kanji: '特', meaning: 'special', onyomi: 'toku', kunyomi: '—' },
  { kanji: '私', meaning: 'I, me, private', onyomi: 'shi', kunyomi: 'watashi, watakushi' },
  { kanji: '始', meaning: 'begin, start, commence', onyomi: 'shi', kunyomi: 'haji-maru, haji-meru' },
  { kanji: '朝', meaning: 'morning', onyomi: 'chou', kunyomi: 'asa' },
  { kanji: '運', meaning: 'carry, transport, luck, fortune', onyomi: 'un', kunyomi: 'hako-bu' },
  { kanji: '終', meaning: 'end, finish', onyomi: 'shuu', kunyomi: 'o-waru' },
  { kanji: '台', meaning: 'pedestal, stand, counter for machines', onyomi: 'dai, tai', kunyomi: 'utena' },
  { kanji: '広', meaning: 'wide, broad, spacious', onyomi: 'kou', kunyomi: 'hiro-i' },
  { kanji: '住', meaning: 'live, dwell, reside, inhabit', onyomi: 'juu, chuu', kunyomi: 'su-mu' },
  { kanji: '無', meaning: 'nothing, without', onyomi: 'mu, bu', kunyomi: 'na-i' },
  { kanji: '真', meaning: 'true, truth, reality', onyomi: 'shin', kunyomi: 'ma, makoto' },
  { kanji: '有', meaning: 'have, possess, exist', onyomi: 'yuu, u', kunyomi: 'a-ru' },
  { kanji: '口', meaning: 'mouth', onyomi: 'kou', kunyomi: 'kuchi' },
  { kanji: '少', meaning: 'few, little', onyomi: 'shou', kunyomi: 'suku-nai, suko-shi' },
  { kanji: '町', meaning: 'town, city, block', onyomi: 'chou', kunyomi: 'machi' },
  { kanji: '料', meaning: 'fee, materials', onyomi: 'ryou', kunyomi: '—' },
  { kanji: '工', meaning: 'craft, construction', onyomi: 'kou, ku, gu', kunyomi: '—' },
  { kanji: '建', meaning: 'build, construct', onyomi: 'ken, kon', kunyomi: 'ta-tsu, ta-teru' },
  { kanji: '空', meaning: 'empty, void, vacant, sky', onyomi: 'kuu', kunyomi: 'sora, kara, a-ku, su-ku, muna-shii' },
  { kanji: '急', meaning: 'hurry, sudden, urgent', onyomi: 'kyuu', kunyomi: 'iso-gu' },
  { kanji: '止', meaning: 'stop, halt', onyomi: 'shi', kunyomi: 'to-maru, to-meru, todo-maru' },
  { kanji: '送', meaning: 'send', onyomi: 'sou', kunyomi: 'oku-ru' },
  { kanji: '切', meaning: 'cut', onyomi: 'setsu, sai', kunyomi: 'ki-ru, ki-reru' },
  { kanji: '転', meaning: 'revolve, turn around, tumble', onyomi: 'ten', kunyomi: 'koro-gasu, koro-garu, koro-geru, koro-bu' },
  { kanji: '研', meaning: 'polish, sharpen', onyomi: 'ken', kunyomi: 'to-gu' },
  { kanji: '足', meaning: 'foot, leg, sufficient', onyomi: 'soku', kunyomi: 'ashi, ta-riru' },
  { kanji: '究', meaning: 'research, study, delve into', onyomi: 'kyuu', kunyomi: 'kiwa-meru' },
  { kanji: '楽', meaning: 'music, pleasure, comfort, enjoyment', onyomi: 'gaku, raku', kunyomi: 'tano-shii, tano-shimu' },
  { kanji: '起', meaning: 'wake up, get up, rouse', onyomi: 'ki', kunyomi: 'o-kiru, oko-su' },
  { kanji: '着', meaning: 'arrive, reach, put on, wear', onyomi: 'jaku, chaku', kunyomi: 'ki-ru, tsu-ku' },
  { kanji: '店', meaning: 'store, shop', onyomi: 'ten', kunyomi: 'mise' },
  { kanji: '病', meaning: 'ill, sick', onyomi: 'byou, hei', kunyomi: 'ya-mu, yamai' },
  { kanji: '質', meaning: 'quality', onyomi: 'shitsu, shichi, chi', kunyomi: 'tachi, tada-su' },
  { kanji: '待', meaning: 'wait', onyomi: 'tai', kunyomi: 'ma-tsu' },
  { kanji: '試', meaning: 'try, attempt, test, experiment', onyomi: 'shi', kunyomi: 'kokoro-miru, tame-su' },
  { kanji: '族', meaning: 'family, tribe', onyomi: 'zoku', kunyomi: '—' },
  { kanji: '銀', meaning: 'silver', onyomi: 'gin', kunyomi: '—' },
  { kanji: '早', meaning: 'early, quick, fast, speedy', onyomi: 'sou, sa', kunyomi: 'haya-i, haya-maru, haya-meru' },
  { kanji: '映', meaning: 'reflect, projection', onyomi: 'ei', kunyomi: 'utsu-ru, ha-eru' },
  { kanji: '親', meaning: 'parent, intimate', onyomi: 'shin', kunyomi: 'oya, shita-shii, shita-shimu' },
  { kanji: '験', meaning: 'effect, testing, verification, experience', onyomi: 'ken, gen', kunyomi: '—' },
  { kanji: '英', meaning: 'distinguished, outstanding, English', onyomi: 'ei', kunyomi: '—' },
  { kanji: '医', meaning: 'medicine, doctor, cure', onyomi: 'i', kunyomi: '—' },
  { kanji: '仕', meaning: 'serve, attend', onyomi: 'shi, ji', kunyomi: 'tsuka-eru' },
  { kanji: '去', meaning: 'leave, go away', onyomi: 'kyo, ko', kunyomi: 'sa-ru' },
  { kanji: '味', meaning: 'taste, flavor', onyomi: 'mi', kunyomi: 'aji, aji-wau' },
  { kanji: '写', meaning: 'copy, transcribe', onyomi: 'sha', kunyomi: 'utsu-su, utsu-ru' },
  { kanji: '字', meaning: 'character, letter', onyomi: 'ji', kunyomi: 'aza' },
  { kanji: '答', meaning: 'answer', onyomi: 'tou', kunyomi: 'kota-eru' },
  { kanji: '夜', meaning: 'night, evening', onyomi: 'ya', kunyomi: 'yo, yoru' },
  { kanji: '音', meaning: 'sound', onyomi: 'in, on', kunyomi: 'oto, ne' },
  { kanji: '注', meaning: 'pour, concentrate on, annotate', onyomi: 'chuu', kunyomi: 'soso-gu, sa-su, tsu-gu' },
  { kanji: '帰', meaning: 'return, go back, come back', onyomi: 'ki', kunyomi: 'kae-ru, kae-su' },
  { kanji: '古', meaning: 'old, ancient', onyomi: 'ko', kunyomi: 'furu-i, furu-su' },
  { kanji: '歌', meaning: 'song, sing', onyomi: 'ka', kunyomi: 'uta, uta-u' },
  { kanji: '買', meaning: 'buy', onyomi: 'bai', kunyomi: 'ka-u' },
  { kanji: '悪', meaning: 'bad, evil', onyomi: 'aku, o', kunyomi: 'waru-i' },
  { kanji: '図', meaning: 'drawing, chart, map, diagram', onyomi: 'zu, to', kunyomi: 'haka-ru' },
  { kanji: '週', meaning: 'week', onyomi: 'shuu', kunyomi: '—' },
  { kanji: '室', meaning: 'room, cellar', onyomi: 'shitsu', kunyomi: 'muro' },
  { kanji: '歩', meaning: 'walk, counter for steps', onyomi: 'fu, ho, bu', kunyomi: 'aru-ku, ayu-mu' },
  { kanji: '風', meaning: 'wind', onyomi: 'fuu, fu', kunyomi: 'kaze, kaza-' },
  { kanji: '紙', meaning: 'paper', onyomi: 'shi', kunyomi: 'kami' },
  { kanji: '黒', meaning: 'black', onyomi: 'koku', kunyomi: 'kuro' },
  { kanji: '花', meaning: 'flower', onyomi: 'ka, ke', kunyomi: 'hana' },
  { kanji: '春', meaning: 'spring', onyomi: 'shun', kunyomi: 'haru' },
  { kanji: '赤', meaning: 'red', onyomi: 'seki, shaku', kunyomi: 'aka-i' },
  { kanji: '青', meaning: 'blue', onyomi: 'sei, shou', kunyomi: 'ao-i' },
  { kanji: '館', meaning: 'building, mansion', onyomi: 'kan', kunyomi: 'yakata' },
  { kanji: '屋', meaning: 'roof, house, shop, dealer, seller', onyomi: 'oku', kunyomi: 'ya' },
  { kanji: '色', meaning: 'color', onyomi: 'shoku, shiki', kunyomi: 'iro' },
  { kanji: '走', meaning: 'run', onyomi: 'sou', kunyomi: 'hashi-ru' },
  { kanji: '秋', meaning: 'autumn, fall', onyomi: 'shuu', kunyomi: 'aki' },
  { kanji: '夏', meaning: 'summer', onyomi: 'ka, ge', kunyomi: 'natsu' },
  { kanji: '習', meaning: 'learn', onyomi: 'shuu', kunyomi: 'nara-u' },
  { kanji: '駅', meaning: 'station', onyomi: 'eki', kunyomi: '—' },
  { kanji: '洋', meaning: 'ocean, sea, Western style', onyomi: 'you', kunyomi: '—' },
  { kanji: '旅', meaning: 'travel, trip, journey', onyomi: 'ryo', kunyomi: 'tabi' },
  { kanji: '服', meaning: 'clothing, admit, obey', onyomi: 'fuku', kunyomi: '—' },
  { kanji: '夕', meaning: 'evening', onyomi: 'seki', kunyomi: 'yuu' },
  { kanji: '借', meaning: 'borrow, rent', onyomi: 'shaku', kunyomi: 'ka-riru' },
  { kanji: '曜', meaning: 'weekday', onyomi: 'you', kunyomi: '—' },
  { kanji: '飲', meaning: 'drink', onyomi: 'in', kunyomi: 'no-mu' },
  { kanji: '肉', meaning: 'meat, flesh', onyomi: 'niku', kunyomi: '—' },
  { kanji: '貸', meaning: 'lend, loan', onyomi: 'tai', kunyomi: 'ka-su, kashi' },
  { kanji: '堂', meaning: 'hall', onyomi: 'dou', kunyomi: '—' },
  { kanji: '鳥', meaning: 'bird, chicken', onyomi: 'chou', kunyomi: 'tori' },
  { kanji: '飯', meaning: 'meal, boiled rice, cooked rice', onyomi: 'han', kunyomi: 'meshi' },
  { kanji: '勉', meaning: 'make efforts, endeavor, study', onyomi: 'ben', kunyomi: 'tsuto-meru' },
  { kanji: '冬', meaning: 'winter', onyomi: 'tou', kunyomi: 'fuyu' },
  { kanji: '昼', meaning: 'daytime, noon', onyomi: 'chuu', kunyomi: 'hiru' },
  { kanji: '茶', meaning: 'tea, brown', onyomi: 'cha, sa', kunyomi: '—' },
  { kanji: '弟', meaning: 'younger brother, brother', onyomi: 'tei, dai, de', kunyomi: 'otouto' },
  { kanji: '牛', meaning: 'cow', onyomi: 'gyuu', kunyomi: 'ushi' },
  { kanji: '魚', meaning: 'fish', onyomi: 'gyo', kunyomi: 'uo, sakana' },
  { kanji: '兄', meaning: 'elder brother', onyomi: 'kyou, kei', kunyomi: 'ani' },
  { kanji: '犬', meaning: 'dog', onyomi: 'ken', kunyomi: 'inu' },
  { kanji: '妹', meaning: 'younger sister', onyomi: 'mai', kunyomi: 'imouto' },
  { kanji: '姉', meaning: 'elder sister', onyomi: 'shi', kunyomi: 'ane' },
  { kanji: '漢', meaning: 'China, kanji, Chinese character', onyomi: 'kan', kunyomi: '—' }
];
