export interface N5Kanji {
  kanji: string;
  meaning: string;
  onyomi: string;
  kunyomi: string;
}

// 80 kanji JLPT N5, urutan & bacaan mengikuti daftar standar JLPT Sensei.
export const N5_KANJI_DATA: N5Kanji[] = [
  { kanji: '日', meaning: 'day, sun', onyomi: 'nichi, jitsu', kunyomi: 'hi, -bi, -ka' },
  { kanji: '一', meaning: 'one', onyomi: 'ichi', kunyomi: 'hito(tsu)' },
  { kanji: '国', meaning: 'country', onyomi: 'koku', kunyomi: 'kuni' },
  { kanji: '人', meaning: 'person', onyomi: 'jin, nin', kunyomi: 'hito' },
  { kanji: '年', meaning: 'year', onyomi: 'nen', kunyomi: 'toshi' },
  { kanji: '大', meaning: 'large, big', onyomi: 'dai, tai', kunyomi: 'oo(kii)' },
  { kanji: '十', meaning: 'ten', onyomi: 'juu', kunyomi: 'tou, to' },
  { kanji: '二', meaning: 'two', onyomi: 'ni, ji', kunyomi: 'futa(tsu)' },
  { kanji: '本', meaning: 'book, true', onyomi: 'hon', kunyomi: 'moto' },
  { kanji: '中', meaning: 'inside, center', onyomi: 'chuu', kunyomi: 'naka, uchi, ata(ru)' },
  { kanji: '長', meaning: 'long, superior', onyomi: 'chou', kunyomi: 'naga(i), osa' },
  { kanji: '出', meaning: 'exit, leave', onyomi: 'shutsu, sui', kunyomi: 'de(ru), da(su)' },
  { kanji: '三', meaning: 'three', onyomi: 'san', kunyomi: 'mi(tsu)' },
  { kanji: '時', meaning: 'time, hour', onyomi: 'ji', kunyomi: 'toki, -doki' },
  { kanji: '行', meaning: 'going, line', onyomi: 'kou, gyou', kunyomi: 'i(ku), yu(ku)' },
  { kanji: '見', meaning: 'see, look', onyomi: 'ken', kunyomi: 'mi(ru), mi(seru)' },
  { kanji: '月', meaning: 'month, moon', onyomi: 'getsu, gatsu', kunyomi: 'tsuki' },
  { kanji: '分', meaning: 'part, minute', onyomi: 'bun, fun', kunyomi: 'wa(keru)' },
  { kanji: '後', meaning: 'behind, later', onyomi: 'go, kou', kunyomi: 'nochi, ushi(ro)' },
  { kanji: '前', meaning: 'in front, before', onyomi: 'zen', kunyomi: 'mae' },
  { kanji: '生', meaning: 'life, birth', onyomi: 'sei, shou', kunyomi: 'i(kiru), u(mu)' },
  { kanji: '五', meaning: 'five', onyomi: 'go', kunyomi: 'itsu(tsu)' },
  { kanji: '間', meaning: 'interval, space', onyomi: 'kan, ken', kunyomi: 'aida, ma' },
  { kanji: '上', meaning: 'above, up', onyomi: 'jou, shou', kunyomi: 'ue, kami, a(geru)' },
  { kanji: '東', meaning: 'east', onyomi: 'tou', kunyomi: 'higashi' },
  { kanji: '四', meaning: 'four', onyomi: 'shi', kunyomi: 'yo(tsu), yon' },
  { kanji: '今', meaning: 'now', onyomi: 'kon, kin', kunyomi: 'ima' },
  { kanji: '金', meaning: 'gold', onyomi: 'kin, kon', kunyomi: 'kane, kana' },
  { kanji: '九', meaning: 'nine', onyomi: 'kyuu, ku', kunyomi: 'kokono(tsu)' },
  { kanji: '入', meaning: 'enter, insert', onyomi: 'nyuu', kunyomi: 'i(ru), hai(ru)' },
  { kanji: '学', meaning: 'study, learning', onyomi: 'gaku', kunyomi: 'mana(bu)' },
  { kanji: '高', meaning: 'tall, expensive', onyomi: 'kou', kunyomi: 'taka(i)' },
  { kanji: '円', meaning: 'circle, yen', onyomi: 'en', kunyomi: 'maru(i)' },
  { kanji: '子', meaning: 'child', onyomi: 'shi, su', kunyomi: 'ko, ne' },
  { kanji: '外', meaning: 'outside', onyomi: 'gai, ge', kunyomi: 'soto, hoka' },
  { kanji: '八', meaning: 'eight', onyomi: 'hachi', kunyomi: 'ya(tsu), you' },
  { kanji: '六', meaning: 'six', onyomi: 'roku', kunyomi: 'mu(tsu)' },
  { kanji: '下', meaning: 'below, down', onyomi: 'ka, ge', kunyomi: 'shita, shimo' },
  { kanji: '来', meaning: 'come, next', onyomi: 'rai, tai', kunyomi: 'kuru, ki' },
  { kanji: '気', meaning: 'spirit, mind, air', onyomi: 'ki, ke', kunyomi: 'iki' },
  { kanji: '小', meaning: 'small, little', onyomi: 'shou', kunyomi: 'chii(sai), ko-' },
  { kanji: '七', meaning: 'seven', onyomi: 'shichi', kunyomi: 'nana(tsu)' },
  { kanji: '山', meaning: 'mountain', onyomi: 'san, sen', kunyomi: 'yama' },
  { kanji: '話', meaning: 'talk, tale', onyomi: 'wa', kunyomi: 'hana(su)' },
  { kanji: '女', meaning: 'woman, female', onyomi: 'jo', kunyomi: 'onna, me' },
  { kanji: '北', meaning: 'north', onyomi: 'hoku', kunyomi: 'kita' },
  { kanji: '午', meaning: 'noon', onyomi: 'go', kunyomi: 'uma' },
  { kanji: '百', meaning: 'hundred', onyomi: 'hyaku', kunyomi: 'momo' },
  { kanji: '書', meaning: 'write', onyomi: 'sho', kunyomi: 'kaku' },
  { kanji: '先', meaning: 'before, ahead', onyomi: 'sen', kunyomi: 'saki, ma(zu)' },
  { kanji: '名', meaning: 'name', onyomi: 'mei, myou', kunyomi: 'na' },
  { kanji: '川', meaning: 'river, stream', onyomi: 'sen', kunyomi: 'kawa' },
  { kanji: '千', meaning: 'thousand', onyomi: 'sen', kunyomi: 'chi' },
  { kanji: '水', meaning: 'water', onyomi: 'sui', kunyomi: 'mizu' },
  { kanji: '半', meaning: 'half, middle', onyomi: 'han', kunyomi: 'naka(ba)' },
  { kanji: '男', meaning: 'male, man', onyomi: 'dan, nan', kunyomi: 'otoko' },
  { kanji: '西', meaning: 'west', onyomi: 'sei, sai', kunyomi: 'nishi' },
  { kanji: '電', meaning: 'electricity', onyomi: 'den', kunyomi: '—' },
  { kanji: '校', meaning: 'school, exam', onyomi: 'kou', kunyomi: '—' },
  { kanji: '語', meaning: 'word, language', onyomi: 'go', kunyomi: 'kata(ru)' },
  { kanji: '土', meaning: 'soil, earth', onyomi: 'do, to', kunyomi: 'tsuchi' },
  { kanji: '木', meaning: 'tree, wood', onyomi: 'boku, moku', kunyomi: 'ki, ko-' },
  { kanji: '聞', meaning: 'hear, listen', onyomi: 'bun, mon', kunyomi: 'ki(ku)' },
  { kanji: '食', meaning: 'eat, food', onyomi: 'shoku, jiki', kunyomi: 'ku(u), ta(beru)' },
  { kanji: '車', meaning: 'car, wheel', onyomi: 'sha', kunyomi: 'kuruma' },
  { kanji: '何', meaning: 'what', onyomi: 'ka', kunyomi: 'nani, nan' },
  { kanji: '南', meaning: 'south', onyomi: 'nan, na', kunyomi: 'minami' },
  { kanji: '万', meaning: 'ten thousand', onyomi: 'man, ban', kunyomi: '—' },
  { kanji: '毎', meaning: 'every', onyomi: 'mai', kunyomi: 'goto(ni)' },
  { kanji: '白', meaning: 'white', onyomi: 'haku, byaku', kunyomi: 'shiro(i)' },
  { kanji: '天', meaning: 'heavens, sky', onyomi: 'ten', kunyomi: 'ama, ame' },
  { kanji: '母', meaning: 'mother', onyomi: 'bo', kunyomi: 'haha, kaa' },
  { kanji: '火', meaning: 'fire', onyomi: 'ka', kunyomi: 'hi, -bi' },
  { kanji: '右', meaning: 'right', onyomi: 'u, yuu', kunyomi: 'migi' },
  { kanji: '読', meaning: 'to read', onyomi: 'doku, toku', kunyomi: 'yo(mu)' },
  { kanji: '友', meaning: 'friend', onyomi: 'yuu', kunyomi: 'tomo' },
  { kanji: '左', meaning: 'left', onyomi: 'sa, sha', kunyomi: 'hidari' },
  { kanji: '休', meaning: 'rest, day off', onyomi: 'kyuu', kunyomi: 'yasu(mu)' },
  { kanji: '父', meaning: 'father', onyomi: 'fu', kunyomi: 'chichi, tou' },
  { kanji: '雨', meaning: 'rain', onyomi: 'u', kunyomi: 'ame, ama' }
];
